- src/commodore/index.spec.ts
- src/commodore/inventory.ts
Previously commodore results for different tenant repos would use the same key in the commodore inventory cache.
This commit prefixes the cache key for the inventory with the path of the repo we're renovating to ensure that we don't share cache keys between different repos.
> Fix caching of Commodore results

- src/commodore/index.ts
- src/commodore/readme.md
- src/index.ts
Instead of exposing a `lieutenantToken` config option which defaults to environment variable `LIEUTENANT_API_TOKEN`, we expose a config option which allows specifying the environment variable from which the token should be read.
With the previous approach, there was no way for users to securely specify different Lieutenant tokens for different repositories, except for providing the token in plain text in the repository's `renovate.json`.
With the new approach, users can provide all the required Lieutenant secrets as environment variables in the Renovate runner execution environment, and users can select an appropriate token for their configured Lieutenant instance.
Note: even though we don't expose the `lieutenantToken` option anymore, we internally still set the field on the config …
> Expose Lieutenant token config only via environment variable

- src/commodore/index.ts
Use the logger's record functionality to provide specific information for the log messages instead of string interpolation.
Follow-up for #9 & #11, doesn't need to appear in the changelog
> Clean up log messages related to Lieutenant API

- src/commodore-docker/__fixtures__/4/params.yml
- src/commodore-docker/__fixtures__/5/params.yml
- src/commodore-docker/__snapshots__/index.spec.ts.snap
- src/commodore-docker/index.spec.ts
- src/commodore-docker/index.ts
- src/commodore-docker/readme.md
This switches to trying to parse any object as a image dependency. That way we can find dependencies such as: https://github.com/projectsyn/component-keycloak/blob/e62be9031c9d4a2fe42d473429da1cef335169c2/class/defaults.yml#L156.
However this could very well lead to false positives. I'm unsure if we should implement this or not. 
> Recursively parse every object

- src/commodore-helm/__fixtures__/1/class/component-name.yml
- src/commodore-helm/__fixtures__/1/class/defaults.yml
- src/commodore-helm/__fixtures__/2/class/defaults.yml
- src/commodore-helm/__fixtures__/2/class/long-component-name.yml
- src/commodore-helm/__fixtures__/3/class/component-name.yml
- src/commodore-helm/__fixtures__/3/class/defaults.yml
- src/commodore-helm/__fixtures__/4/class/component-name.yml
- src/commodore-helm/__fixtures__/4/class/defaults.yml
- src/commodore-helm/__fixtures__/5/class/component-name-2.yml
- src/commodore-helm/__fixtures__/5/class/component-name.yml
- src/commodore-helm/__fixtures__/5/class/defaults.yml
- src/commodore-helm/__fixtures__/6/class/component-name.yml
- src/commodore-helm/__fixtures__/6/class/defaults.yml
- src/commodore-helm/__snapshots__/index.spec.ts.snap
- src/commodore-helm/index.spec.ts
- src/commodore-helm/index.ts
- src/commodore-helm/readme.md
- src/commodore/index.spec.ts
- src/index.ts
- src/test/util.ts
This PR introduces a new manager `commodore-helm`, which extracts Helm charts from the component defaults. This manager is implemented with `extractAllPackageFiles`, because we need to correlate information found in `class/defaults.yml` with information found in `class/<component-name>yml`.
The manager currently only supports Helm charts for which the version is specified in field `charts` in `parameters.<component_name>` and which are fetched by Kapitan using the Helm dependency type with their version indicated by `${<component_name>:charts:<chart_name>}`.
The manager currently can't extract the Helm repository URL for Helm charts which are specified in different ways (e.g. using Kapitan HTTPS dependencies).
as …
> Add support for renovating Helm chart versions in component defaults

- src/commodore-helm/__fixtures__/7/class/component-name.yml
- src/commodore-helm/__fixtures__/7/class/defaults.yml
- src/commodore-helm/__snapshots__/index.spec.ts.snap
- src/commodore-helm/index.spec.ts
- src/commodore-helm/index.ts
- src/commodore-helm/readme.md
Follow-up for #17 to implement support for the new best-practice Helm chart dependency specification format defined in https://github.com/projectsyn/documentation/pull/150
> Add support for new best-practice Helm chart dependency format

- src/commodore-helm/index.spec.ts
- src/commodore-helm/index.ts
This allows us to enable the manager globally without Renovate exiting with an error if the manager is active on a repo which isn't a component repo.
> Change error log messages to warnings in commodore-helm

- src/commodore-helm/index.ts
- src/commodore/index.ts
Yarn suddenly decided two variables can be null and really doesn't like that..
Ignore as this wasn't released yet and really doesn't help in the changelog
> Fix two null value errors

- src/commodore/index.ts
- src/commodore/readme.md
- src/commodore/util.spec.ts
The updated regex will not extract wrong regions from subdirectory in cloud directory.
I.E `cloud/cloudscale/foo/bar` will not get any region instead of region `foo/bar`.
> Fix default cloud region regex to not extract regions with slashes

- renovate.json
Since we're running renovate with `schedule:weekly`, increasing the hourly PR limit makes sense, since we only get one batch of PRs per week, and the default of 2 PRs isn't really sufficient to get PRs for all dependencies which were upgraded during a whole week.
> Allow up to 5 Renovate PRs per week

- requirements.txt
This will ensure that future Commodore-Renovate PRs have the new YAML indentation introduced in v1.12.0
> Update Commodore to v1.12.0

- Dockerfile
Required by Commodore v1.15.0/Kapitan 0.31.0, cf. https://github.com/projectsyn/commodore/commit/8896815980d82bb05b3d4132aa60065b8b02b0ca
Follow-up to #118 
> Add missing `libmagic1` in container image

- Dockerfile
This commit uses the same base image as Renovate uses as of https://github.com/renovatebot/docker-renovate-full/commit/988c3b0a5e34e58a1b4ef6195e27b7103f36a199
This should fix the dependency lookup error logged by Renovate, and should allow us to upgrade Python again.
> Switch from `renovate/buildpack` to `containerbase/base`

- src/commodore/__fixtures__/1/params.yml
- src/commodore/__snapshots__/index.spec.ts.snap
- src/commodore/index.spec.ts
- src/commodore/index.ts
- src/commodore/readme.md
GitHub releases support the `releaseTimestamp` field, which is necessary for `minimumReleaseAge` to work.
It's not the prettiest implementation, but it works. Happy to hear suggestions for how to improve it.
> Use GitHub releases instead of git refs where possible

- .github/workflows/test.yml
- tsconfig.json
Additionally, the PR updates the GitHub action to run `yarn build` so we notice issues with TypeScript target JS versions before merging.
> Update TypeScript config to correctly target ES2019

- .github/workflows/test.yml
- Dockerfile
Containerbase v11 has removed the tool `bin/` directories from the PATH, which breaks commodore-renovate, since we rely on `commodore` being available in the PATH (cf. https://github.com/containerbase/base/commit/2ca2238b1cb73b9c79270c46e82aff16f802b91f).
This commit adjusts the Dockerfile to prepend the installed python tool directory `bin/` to the PATH.
Follow-up to #299 
> Make the Commodore binary available in PATH with containerbase v11

- Dockerfile
This fixes issues with `make gen-golden` for components which no longer compile with Python reclass.
> Patch kapitan in commodore-renovate container image to use reclass-rs

- Dockerfile
- renovate.json
We update the regex managers to use `packageName` instead of `lookupName` as required for Renovate v32+.
Additionally, we add optional comment field `versionTemplate` so we can handle custom Git tag formats such as `kustomize/vX.Y.Z`.
> Update Renovate regex managers for Dockerfile

- .github/workflows/test.yml
- Dockerfile
The `install_kustomize.sh` script has some logic which resolves symlinks in the install directory path. However, this messes up somehow when resolving the symlink `/usr/local/bin/` which points to `/opt/containerbase/bin`. To avoid this issue, we directly provide `/opt/containerbase/bin` as the install directory.
> Fix install of kustomize in container image

- Dockerfile
containerbase has removed the `/etc/passwd` entry for UID 1000 at some point. We run `useradd` to create an entry for UID 1000 so we can clone Git repos over SSH.
> Create real user for UID 1000 so Git SSH clones work

- Dockerfile
We need the home directory so we can save the git.vshn.net host keys when running commodore-renovate for tenant repos on git.vshn.net.
Follow-up for #371 
> Create home directory for custom user

- Dockerfile
The containerbase image has a bunch of extra logic in the entrypoint script which makes it tricky to setup a custom user with correct environment variables.
Instead we just switch to using the new UID of user ubuntu (`12021`) for the final container image.
Replaces #371 #376 #377
> Switch to using UID 12021 of user `ubuntu`

- src/commodore-helm/index.spec.ts
- src/commodore-helm/index.ts
We need to anchor the beginning of the `fileMatch` commodore-helm regex `class/[^.].ya?ml$` so that we don't accidentally match any files in golden tests whose name or path contains the fragment `class/`, such as component-rook-ceph's `rbd-extra-storageclass` test case.
Added a test case which tests the `fileMatch` regex pattern against some representative cases.
> Fix `fileMatch` for commodore-helm manager

- .github/workflows/test.yml
- Dockerfile
* Run `commodore version` when validating built container image
* Remove golang install from Dockerfile since gojsonnet 0.21.0 provides prebuilt wheels
* Use `commodore tool install` to install Commodore's binary dependencies
> Update Dockerfile for recent Commodore versions
